20140822/roo/4.02.0: pprint

diff --git a/20140822/roo/4.02.0/raw/patoline b/20140822/roo/4.02.0/raw/patoline
--- a/20140822/roo/4.02.0/raw/patoline
+++ b/20140822/roo/4.02.0/raw/patoline
@@ -3188,3 +3188,165 @@ tools/camomilelocaledef.opt --file locales/pt_BR.txt locales
 tools/camomilelocaledef.opt --file locales/pt_PT.txt locales 
 tools/camomilelocaledef.opt --file locales/pt_PT_PREEURO.txt locales 
 tools/camomilelocaledef.opt --file locales/ro.txt locales 
+tools/camomilelocaledef.opt --file locales/ro_RO.txt locales 
+tools/camomilelocaledef.opt --file locales/root.txt locales 
+tools/camomilelocaledef.opt --file locales/ru.txt locales 
+tools/camomilelocaledef.opt --file locales/ru_RU.txt locales 
+tools/camomilelocaledef.opt --file locales/ru_UA.txt locales 
+tools/camomilelocaledef.opt --file locales/sa.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/sa_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/sh.txt locales 
+tools/camomilelocaledef.opt --file locales/sh_YU.txt locales 
+tools/camomilelocaledef.opt --file locales/sk.txt locales 
+tools/camomilelocaledef.opt --file locales/sk_SK.txt locales 
+tools/camomilelocaledef.opt --file locales/sl.txt locales 
+tools/camomilelocaledef.opt --file locales/sl_SI.txt locales 
+tools/camomilelocaledef.opt --file locales/so.txt locales 
+tools/camomilelocaledef.opt --file locales/so_DJ.txt locales 
+tools/camomilelocaledef.opt --file locales/so_ET.txt locales 
+tools/camomilelocaledef.opt --file locales/so_KE.txt locales 
+tools/camomilelocaledef.opt --file locales/so_SO.txt locales 
+tools/camomilelocaledef.opt --file locales/sq.txt locales 
+tools/camomilelocaledef.opt --file locales/sq_AL.txt locales 
+tools/camomilelocaledef.opt --file locales/sr.txt locales 
+tools/camomilelocaledef.opt --file locales/sr_YU.txt locales 
+tools/camomilelocaledef.opt --file locales/sv.txt locales 
+tools/camomilelocaledef.opt --file locales/sv_FI.txt locales 
+tools/camomilelocaledef.opt --file locales/sv_SE.txt locales 
+tools/camomilelocaledef.opt --file locales/sw.txt locales 
+tools/camomilelocaledef.opt --file locales/sw_KE.txt locales 
+tools/camomilelocaledef.opt --file locales/sw_TZ.txt locales 
+tools/camomilelocaledef.opt --file locales/syr.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/syr_SY.txt locales 
+tools/camomilelocaledef.opt --file locales/ta.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/ta_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/te.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/te_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/test_1.txt locales 
+tools/camomilelocaledef.opt --file locales/th.txt locales 
+Warning : file loading is not supported.
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/th_TH.txt locales 
+tools/camomilelocaledef.opt --file locales/ti.txt locales 
+tools/camomilelocaledef.opt --file locales/ti_ER.txt locales 
+tools/camomilelocaledef.opt --file locales/ti_ET.txt locales 
+tools/camomilelocaledef.opt --file locales/tr.txt locales 
+tools/camomilelocaledef.opt --file locales/tr_TR.txt locales 
+tools/camomilelocaledef.opt --file locales/tt.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/tt_RU.txt locales 
+tools/camomilelocaledef.opt --file locales/uk.txt locales 
+tools/camomilelocaledef.opt --file locales/uk_UA.txt locales 
+tools/camomilelocaledef.opt --file locales/ur.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/ur_PK.txt locales 
+tools/camomilelocaledef.opt --file locales/uz.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/uz_UZ.txt locales 
+tools/camomilelocaledef.opt --file locales/vi.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/vi_VN.txt locales 
+tools/camomilelocaledef.opt --file locales/zh.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_CN.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_HK.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_MO.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_SG.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_TW.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_TW_STROKE.txt locales 
+tools/camomilelocaledef.opt --file locales/zh__PINYIN.txt locales 
+rm toolslib/colLexer.ml internal/uReStrLexer.ml toolslib/colParser.mli toolslib/colParser.ml
+files= &&\
+	if [ -f camomileLibrary.cmx ]; then files=camomileLibrary.cmx; fi && \
+	if [ -f camomileLibrary.cma ]; then files="camomileLibrary.cma $files"; fi && \
+	if [ -f camomileLibrary.cmxa ]; then files="camomileLibrary.cmxa $files"; fi && \
+	if [ -f camomileLibraryDefault.cmx ]; then files="camomileLibraryDefault.cmx $files"; fi && \
+	if [ -f camomileLibraryDyn.cmx ]; then files="camomileLibraryDyn.cmx $files"; fi && \
+	if [ -f camomile.cma ]; then files="camomile.cma $files"; fi&& \
+	if [ -f camomile.cmxa ]; then files="camomile.cmxa $files"; fi&& \
+	if [ -f camomile.cmxs ]; then files="camomile.cmxs $files"; fi&& \
+	if [ -f camomile.a ]; then files="camomile.a $files"; fi && \
+	ocamlfind install camomile $files META camomileLibrary.mli camomileLibraryDefault.mli camomileLibraryDyn.mli camomileLibrary.cmi camomileLibraryDefault.cmi camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cma
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmxa
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.cma
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.cmxa
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.cmxs
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.a
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/META
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/database
+cp -f database/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/database || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/charmaps
+cp -f charmaps/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/charmaps || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/mappings
+cp -f mappings/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/mappings || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/locales
+cp -f locales/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/locales || true
+Installing camomile.0.8.5.
+
+
+#=== ERROR while installing camlimages.4.1.1 ==================================#
+# opam-version         1.2.0~beta4 (b20433ccd4fb06c854e7d9af73b8f310c42a6b5c)
+# os                   linux
+# command              omake --configure
+# path                 /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1
+# compiler             4.02.0+trunk
+# exit-code            2
+# env-file             /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5430-2c871f.env
+# stdout-file          /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5430-2c871f.out
+# stderr-file          /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5430-2c871f.err
+### stdout ###
+# ...[truncated]
+# Warning: Supported: all_formats supported
+# Warning: gifanim is not built: it requires gif lablgtk2
+# Warning: Supported: all_formats supported
+# Warning: tiffps is not built: it requires tiff jpeg ps
+# Warning: Supported: all_formats supported
+# *** omake: finished reading OMakefiles (1.20 sec)
+# - build src jis_unicode.cmo
+# + ocamlfind ocamlc -warn-error A -g -I . -c jis_unicode.ml
+# *** omake: 190/546 targets are up to date
+# *** omake: failed (4.11 sec, 33/33 scans, 26/47 rules, 110/412 digests)
+### stderr ###
+# ...[truncated]
+# ocamlfind: Package `lablgtk2' not found
+# *** omake: warning: stdout is not a tty, disabling the progress bar
+#    (use --progress to override).
+# File "jis_unicode.ml", line 18, characters 15-27:
+# Warning 3: deprecated: Array.create
+# File "jis_unicode.ml", line 1:
+# Error: Some fatal warnings were triggered (1 occurrences)
+# *** omake: targets were not rebuilt because of errors:
+#    src/jis_unicode.cmo
+#       depends on: src/jis_unicode.ml
+
+
+=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+These actions have been completed successfully
+ - install   camlp4.4.02.0
+ - install   sqlite3-ocaml.2.0.6
+ - install   camomile.0.8.5
+ - install   dypgen.20120619-1
+ - install   camlzip.1.05
+ - install   omake.0.9.8.6-0.rc1
+The following failed
+ - install   camlimages.4.1.1
+Due to the errors, the following have been cancelled
+ - install   patoline.0.1
+
+The former state can be restored with opam switch import "/home/opam/.opam/4.02.0+trunk/backup/state-20140723024238.export"
+'opam install patoline' failed.
