centos-7/4.01.0/20140915: riak

diff --git a/centos-7/4.01.0/20140915/raw/riak b/centos-7/4.01.0/20140915/raw/riak
--- a/centos-7/4.01.0/20140915/raw/riak
+++ b/centos-7/4.01.0/20140915/raw/riak
@@ -1683,3 +1683,266 @@ Removed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib
 Uninstallation successful.
 make[2]: Entering directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/piqilib'
 make[2]: `libpiqilib_stubs.a' is up to date.
+ocamlfind ocamlopt -a             -cclib -lpiqilib_stubs    -o piqilib.cmxa piqi_version.cmx piqloc.cmx piqi_util.cmx piq_ast.cmx piqi_lang_piqi.cmx piqi_c.cmx piqi_config.cmx piqi_iolist.cmx piqi_graph.cmx piqi_name.cmx piqi_common.cmx piqi_file.cmx piqi_main.cmx piqi_protobuf.cmx piqi_db.cmx piq_lexer.cmx piq_parser.cmx piq_gen.cmx piqi_objstore.cmx piqobj.cmx piqobj_common.cmx piqobj_to_protobuf.cmx piqobj_of_protobuf.cmx piqobj_to_piq.cmx piqobj_of_piq.cmx piqi.cmx piqi_pp.cmx piqi_json_parser.cmx piqi_json_gen.cmx piqi_json.cmx piqi_base64.cmx piqobj_to_json.cmx piqobj_of_json.cmx piqi_xml.cmx piqobj_to_xml.cmx piqobj_of_xml.cmx piq.cmx piqi_convert.cmx piqirun_ext.cmx piqi_light.cmx piqi_getopt.cmx
+make[2]: Leaving directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/piqilib'
+
+Installing library with ocamlfind
+ocamlfind install  piqilib META piqilib.cmxa piqilib.a libpiqilib_stubs.a piq.cmi piq_ast.cmi piq_gen.cmi piq_lexer.cmi piq_parser.cmi piqi.cmi piqi_base64.cmi piqi_c.cmi piqi_common.cmi piqi_config.cmi piqi_convert.cmi piqi_db.cmi piqi_file.cmi piqi_getopt.cmi piqi_graph.cmi piqi_iolist.cmi piqi_json.cmi piqi_json_gen.cmi piqi_json_parser.cmi piqi_json_type.cmi piqi_lang_piqi.cmi piqi_light.cmi piqi_main.cmi piqi_name.cmi piqi_objstore.cmi piqi_pp.cmi piqi_protobuf.cmi piqi_util.cmi piqi_version.cmi piqi_xml.cmi piqi_xml_type.cmi piqirun_ext.cmi piqloc.cmi piqobj.cmi piqobj_common.cmi piqobj_of_json.cmi piqobj_of_piq.cmi piqobj_of_protobuf.cmi piqobj_of_xml.cmi piqobj_to_json.cmi piqobj_to_piq.cmi piqobj_to_protobuf.cmi piqobj_to_xml.cmi piqirun_ext.mli piqilib.cma
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqilib.cma
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqirun_ext.mli
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_to_xml.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_to_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_to_piq.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_to_json.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_of_xml.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_of_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_of_piq.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_of_json.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj_common.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqobj.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqloc.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqirun_ext.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_xml_type.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_xml.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_version.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_util.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_pp.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_objstore.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_name.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_main.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_light.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_lang_piqi.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_json_type.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_json_parser.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_json_gen.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_json.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_iolist.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_graph.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_getopt.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_file.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_db.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_convert.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_config.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_common.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_c.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi_base64.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqi.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piq_parser.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piq_lexer.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piq_gen.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piq_ast.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piq.cmi
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/libpiqilib_stubs.a
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqilib.a
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/piqilib.cmxa
+Installed /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqilib/META
+
+Installation successful.
+/home/opam/.opam/4.01.0/build/piqi.0.6.5/make/piqi-fix-libinstall piqilib lib
+make[1]: Leaving directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/piqilib'
+install -d /home/opam/.opam/4.01.0/bin
+install piqi-tools/piqi /home/opam/.opam/4.01.0/bin
+ocamlfind remove piqi
+ocamlfind: [WARNING] No such directory: /home/opam/.opam/4.01.0/lib/piqi
+make -C deps uninstall
+make[1]: Entering directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/deps'
+set -e; \
+for dir in   ; do \
+	make -C $dir uninstall; \
+done
+make[1]: Leaving directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/deps'
+test -d  || mkdir -p 
+ocamlfind install piqi `ls /home/opam/.opam/4.01.0/build/piqi.0.6.5/build/lib/ocaml/piqi/*`
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_to_xml.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_to_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_to_piq.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_to_json.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_of_xml.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_of_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_of_piq.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_of_json.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj_common.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqobj.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqloc.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun_ext.mli
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun_ext.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun.cmxa
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun.cma
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqirun.a
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqilib.cmxa
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqilib.cma
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqilib.a
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_xml_type.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_xml.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_version.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_util.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_protobuf.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_pp.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_objstore.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_name.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_main.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_light.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_lang_piqi.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_json_type.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_json_parser.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_json_gen.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_json.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_iolist.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_graph.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_getopt.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_file.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_db.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_convert.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_config.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_common.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_c.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi_base64.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piqi.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piq_parser.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piq_lexer.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piq_gen.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piq_ast.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/piq.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_openin.ml
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_openin.cmo
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_openin.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_labelscope.ml
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_labelscope.cmo
+Installed /home/opam/.opam/4.01.0/lib/piqi/pa_labelscope.cmi
+Installed /home/opam/.opam/4.01.0/lib/piqi/libpiqilib_stubs.a
+Installed /home/opam/.opam/4.01.0/lib/piqi/META
+make -C deps install
+make[1]: Entering directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/deps'
+set -e; \
+for dir in   ; do \
+	make -C $dir install; \
+done
+make[1]: Leaving directory `/home/opam/.opam/4.01.0/build/piqi.0.6.5/deps'
+install -d /home/opam/.opam/4.01.0/bin
+install piqic/piqic /home/opam/.opam/4.01.0/bin
+Installing piqi.0.6.5.
+Building riak-pb.1.0.0:
+  ./configure
+  make
+  make install
+
+Configuration: 
+ocamlfind: ........................................... /home/opam/.opam/4.01.0/bin/ocamlfind
+ocamlc: .............................................. /home/opam/.opam/4.01.0/bin/ocamlc.opt
+ocamlopt: ............................................ /home/opam/.opam/4.01.0/bin/ocamlopt.opt
+ocamlbuild: .......................................... /home/opam/.opam/4.01.0/bin/ocamlbuild
+Package name: ........................................ Riak OCaml Protobuffs
+Package version: ..................................... 0.9
+os_type: ............................................. Unix
+system: .............................................. linux
+architecture: ........................................ amd64
+ccomp_type: .......................................... cc
+ocaml_version: ....................................... 4.01.0
+standard_library_default: ............................ /home/opam/.opam/4.01.0/lib/ocaml
+standard_library: .................................... /home/opam/.opam/4.01.0/lib/ocaml
+standard_runtime: .................................... /home/opam/.opam/4.01.0/bin/ocamlrun
+bytecomp_c_compiler: ................................. gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC
+native_c_compiler: ................................... gcc -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT
+model: ............................................... default
+ext_obj: ............................................. .o
+ext_asm: ............................................. .s
+ext_lib: ............................................. .a
+ext_dll: ............................................. .so
+default_executable_name: ............................. a.out
+systhread_supported: ................................. true
+Install architecture-independent files dir: .......... /usr/local
+Install architecture-dependent files in dir: ......... $prefix
+User executables: .................................... $exec_prefix/bin
+System admin executables: ............................ $exec_prefix/sbin
+Program executables: ................................. $exec_prefix/libexec
+Read-only single-machine data: ....................... $prefix/etc
+Modifiable architecture-independent data: ............ $prefix/com
+Modifiable single-machine data: ...................... $prefix/var
+Object code libraries: ............................... $exec_prefix/lib
+Read-only arch-independent data root: ................ $prefix/share
+Read-only architecture-independent data: ............. $datarootdir
+Info documentation: .................................. $datarootdir/info
+Locale-dependent data: ............................... $datarootdir/locale
+Man documentation: ................................... $datarootdir/man
+Documentation root: .................................. $datarootdir/doc/$pkg_name
+HTML documentation: .................................. $docdir
+DVI documentation: ................................... $docdir
+PDF documentation: ................................... $docdir
+PS documentation: .................................... $docdir
+findlib_version: ..................................... 1.5.2
+is_native: ........................................... true
+suffix_program: ...................................... 
+Remove a file.: ...................................... rm -f
+Remove a directory.: ................................. rm -rf
+Turn ocaml debug flag on: ............................ true
+Turn ocaml profile flag on: .......................... false
+Compiler support generation of .cmxs.: ............... true
+OCamlbuild additional flags: ......................... 
+Create documentations: ............................... true
+Compile tests executable and library and run them: ... false
+pkg_piqi: ............................................ /home/opam/.opam/4.01.0/lib/piqi
+pkg_piqi_runtime: .................................... /home/opam/.opam/4.01.0/lib/piqi
+
+ocaml setup.ml -build 
+make[1]: Entering directory `/home/opam/.opam/4.01.0/build/riak-pb.1.0.0'
+piqi of-proto -I ./pb/ ./pb/riak.proto -o ./riak.proto.piqi
+sh: protoc: command not found
+command execution failed: protoc -I./pb/ --include_imports --descriptor_set_out=./pb/riak.proto.pb ./pb/riak.proto
+make[1]: *** [piqi] Error 1
+make[1]: Leaving directory `/home/opam/.opam/4.01.0/build/riak-pb.1.0.0'
+E: Failure("Command 'make -f Makefile.piqi' terminated with error code 2")
+make: *** [build] Error 1
+Removing riak-pb.1.0.0.
+[ERROR] The compilation of riak-pb.1.0.0 failed.
+  ocamlfind remove riak-pb
+ocamlfind: [WARNING] No such directory: /home/opam/.opam/4.01.0/lib/riak-pb
+
+#==================== ERROR while installing riak-pb.1.0.0 ====================#
+# opam-version         1.2.0~beta4
+# os                   linux
+# command              make
+# path                 /home/opam/.opam/4.01.0/build/riak-pb.1.0.0
+# compiler             4.01.0
+# exit-code            2
+# env-file             /home/opam/.opam/4.01.0/build/riak-pb.1.0.0/riak-pb-5958-6cc03f.env
+# stdout-file          /home/opam/.opam/4.01.0/build/riak-pb.1.0.0/riak-pb-5958-6cc03f.out
+# stderr-file          /home/opam/.opam/4.01.0/build/riak-pb.1.0.0/riak-pb-5958-6cc03f.err
+### stdout ###
+# ...[truncated]
+# OCamlbuild additional flags: ......................... 
+# Create documentations: ............................... true
+# Compile tests executable and library and run them: ... false
+# pkg_piqi: ............................................ /home/opam/.opam/4.01.0/lib/piqi
+# pkg_piqi_runtime: .................................... /home/opam/.opam/4.01.0/lib/piqi
+# 
+# ocaml setup.ml -build 
+# make[1]: Entering directory `/home/opam/.opam/4.01.0/build/riak-pb.1.0.0'
+# piqi of-proto -I ./pb/ ./pb/riak.proto -o ./riak.proto.piqi
+# make[1]: Leaving directory `/home/opam/.opam/4.01.0/build/riak-pb.1.0.0'
+### stderr ###
+# sh: protoc: command not found
+# command execution failed: protoc -I./pb/ --include_imports --descriptor_set_out=./pb/riak.proto.pb ./pb/riak.proto
+# make[1]: *** [piqi] Error 1
+# E: Failure("Command 'make -f Makefile.piqi' terminated with error code 2")
+# make: *** [build] Error 1
+
+
+
+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Error report =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+These actions have been completed successfully
+ - install   piqi.0.6.5
+ - install   lwt.2.4.5
+ - install   ulex.1.1
+ - install   easy-format.1.0.2
+ - install   xmlm.1.2.0
+ - install   camlp4.4.01.0
+ - install   ounit.2.0.0
+The following failed
+ - install   riak-pb.1.0.0
+Due to the errors, the following have been cancelled
+ - install   riak.1.0.0
+
+The former state can be restored with opam switch import "/home/opam/.opam/4.01.0/backup/state-20140815100308.export"
+'opam install riak' failed.
