20140528/roo/4.02.0: patoline

diff --git a/20140528/roo/4.02.0/raw/patoline b/20140528/roo/4.02.0/raw/patoline
--- a/20140528/roo/4.02.0/raw/patoline
+++ b/20140528/roo/4.02.0/raw/patoline
@@ -3023,3 +3023,101 @@ tools/camomilelocaledef.opt --file locales/tr_TR.txt locales
 tools/camomilelocaledef.opt --file locales/tt.txt locales 
 Warning : normalization option is not supported
 tools/camomilelocaledef.opt --file locales/tt_RU.txt locales 
+tools/camomilelocaledef.opt --file locales/uk.txt locales 
+tools/camomilelocaledef.opt --file locales/uk_UA.txt locales 
+tools/camomilelocaledef.opt --file locales/ur.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/ur_PK.txt locales 
+tools/camomilelocaledef.opt --file locales/uz.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/uz_UZ.txt locales 
+tools/camomilelocaledef.opt --file locales/vi.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/vi_VN.txt locales 
+tools/camomilelocaledef.opt --file locales/zh.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_CN.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_HK.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_MO.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_SG.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_TW.txt locales 
+tools/camomilelocaledef.opt --file locales/zh_TW_STROKE.txt locales 
+tools/camomilelocaledef.opt --file locales/zh__PINYIN.txt locales 
+rm toolslib/colLexer.ml internal/uReStrLexer.ml toolslib/colParser.mli toolslib/colParser.ml
+files= &&\
+	if [ -f camomileLibrary.cmx ]; then files=camomileLibrary.cmx; fi && \
+	if [ -f camomileLibrary.cma ]; then files="camomileLibrary.cma $files"; fi && \
+	if [ -f camomileLibrary.cmxa ]; then files="camomileLibrary.cmxa $files"; fi && \
+	if [ -f camomileLibraryDefault.cmx ]; then files="camomileLibraryDefault.cmx $files"; fi && \
+	if [ -f camomileLibraryDyn.cmx ]; then files="camomileLibraryDyn.cmx $files"; fi && \
+	if [ -f camomile.cma ]; then files="camomile.cma $files"; fi&& \
+	if [ -f camomile.cmxa ]; then files="camomile.cmxa $files"; fi&& \
+	if [ -f camomile.a ]; then files="camomile.a $files"; fi && \
+	ocamlfind install camomile $files META camomileLibrary.mli camomileLibraryDefault.mli camomileLibraryDyn.mli camomileLibrary.cmi camomileLibraryDefault.cmi camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmi
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.mli
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cma
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibrary.cmxa
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDefault.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomileLibraryDyn.cmx
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.cma
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.cmxa
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/camomile.a
+Installed /home/opam/.opam/4.02.0+trunk/lib/camomile/META
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/database
+cp -f database/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/database || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/charmaps
+cp -f charmaps/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/charmaps || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/mappings
+cp -f mappings/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/mappings || true
+mkdir -p '/home/opam/.opam/4.02.0+trunk/share'/camomile/locales
+cp -f locales/*.mar '/home/opam/.opam/4.02.0+trunk/share'/camomile/locales || true
+Installing camomile.0.8.5.
+
+[ERROR] Due to some errors while processing camlimages.4.1.1, the following actions will NOT proceed:
+ - install patoline.0.1
+
+===== ERROR while installing camlimages.4.1.1 =====
+# opam-version         1.1.1
+# os                   linux
+# command              omake --configure
+# path                 /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1
+# compiler             4.02.0+trunk
+# exit-code            2
+# env-file             /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5634-865888.env
+# stdout-file          /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5634-865888.out
+# stderr-file          /home/opam/.opam/4.02.0+trunk/build/camlimages.4.1.1/camlimages-5634-865888.err
+### stdout ###
+# ...[truncated]
+# Warning: Supported: all_formats supported graphics
+# Warning: gifanim is not built: it requires gif lablgtk2
+# Warning: Supported: all_formats supported graphics
+# Warning: tiffps is not built: it requires tiff jpeg ps
+# Warning: Supported: all_formats supported graphics
+# *** omake: finished reading OMakefiles (6.57 sec)
+# - build src mstring.o
+# + ocamlfind ocamlopt -package graphics -warn-error A -I . -c mstring.ml
+# *** omake: 216/566 targets are up to date
+# *** omake: failed (15.31 sec, 42/42 scans, 32/55 rules, 127/457 digests)
+### stderr ###
+# ...[truncated]
+# Warning 3: deprecated feature: String.set
+# File "mstring.ml", line 160, characters 2-32:
+# Warning 3: deprecated feature: String.set
+# File "mstring.ml", line 1:
+# Error: Some fatal warnings were triggered (13 occurrences)
+# *** omake: targets were not rebuilt because of errors:
+#    src/mstring.cmx
+#       depends on: src/mstring.ml
+#    src/mstring.o
+#       depends on: src/mstring.ml
+
+
+The former state can be restored with opam switch import -f "/home/opam/.opam/4.02.0+trunk/backup/state-20140428194420.export"
+'opam install patoline' failed.
