centos-7/4.01.0/20141003: pa_ounit

diff --git a/centos-7/4.01.0/20141003/raw/patoline b/centos-7/4.01.0/20141003/raw/patoline
--- a/centos-7/4.01.0/20141003/raw/patoline
+++ b/centos-7/4.01.0/20141003/raw/patoline
@@ -1878,3 +1878,166 @@ tools/camomilelocaledef.opt --file locales/lt_LT.txt locales
 tools/camomilelocaledef.opt --file locales/de_DE.txt locales 
 tools/camomilelocaledef.opt --file locales/sr_YU.txt locales 
 tools/camomilelocaledef.opt --file locales/de_LU.txt locales 
+tools/camomilelocaledef.opt --file locales/es_AR.txt locales 
+tools/camomilelocaledef.opt --file locales/fr_MC.txt locales 
+tools/camomilelocaledef.opt --file locales/ta_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/fa_IR.txt locales 
+tools/camomilelocaledef.opt --file locales/sa.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/ms_BN.txt locales 
+tools/camomilelocaledef.opt --file locales/fr_FR_PREEURO.txt locales 
+tools/camomilelocaledef.opt --file locales/mk.txt locales 
+tools/camomilelocaledef.opt --file locales/fi_FI.txt locales 
+tools/camomilelocaledef.opt --file locales/pa_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/en_AU.txt locales 
+tools/camomilelocaledef.opt --file locales/syr_SY.txt locales 
+tools/camomilelocaledef.opt --file locales/no_NO.txt locales 
+tools/camomilelocaledef.opt --file locales/ka.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/ja.txt locales 
+Warning : strength option is not supported
+tools/camomilelocaledef.opt --file locales/pt_PT_PREEURO.txt locales 
+tools/camomilelocaledef.opt --file locales/pt_BR.txt locales 
+tools/camomilelocaledef.opt --file locales/en_MT.txt locales 
+tools/camomilelocaledef.opt --file locales/ga.txt locales 
+tools/camomilelocaledef.opt --file locales/az_AZ.txt locales 
+tools/camomilelocaledef.opt --file locales/fa_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/ru_UA.txt locales 
+tools/camomilelocaledef.opt --file locales/lv.txt locales 
+tools/camomilelocaledef.opt --file locales/da.txt locales 
+tools/camomilelocaledef.opt --file locales/es_PR.txt locales 
+tools/camomilelocaledef.opt --file locales/ca.txt locales 
+tools/camomilelocaledef.opt --file locales/en_ZW.txt locales 
+tools/camomilelocaledef.opt --file locales/ar_DZ.txt locales 
+tools/camomilelocaledef.opt --file locales/lt.txt locales 
+tools/camomilelocaledef.opt --file locales/hy_AM.txt locales 
+tools/camomilelocaledef.opt --file locales/sh.txt locales 
+tools/camomilelocaledef.opt --file locales/es_DO.txt locales 
+tools/camomilelocaledef.opt --file locales/da_DK.txt locales 
+tools/camomilelocaledef.opt --file locales/es_PY.txt locales 
+tools/camomilelocaledef.opt --file locales/en_MH.txt locales 
+tools/camomilelocaledef.opt --file locales/en_ZA.txt locales 
+tools/camomilelocaledef.opt --file locales/hy_AM_REVISED.txt locales 
+tools/camomilelocaledef.opt --file locales/he.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/fr_CH.txt locales 
+tools/camomilelocaledef.opt --file locales/mr_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/root.txt locales 
+tools/camomilelocaledef.opt --file locales/eu_ES.txt locales 
+tools/camomilelocaledef.opt --file locales/no_NO_NY.txt locales 
+tools/camomilelocaledef.opt --file locales/es_BO.txt locales 
+tools/camomilelocaledef.opt --file locales/es_EC.txt locales 
+tools/camomilelocaledef.opt --file locales/om_KE.txt locales 
+tools/camomilelocaledef.opt --file locales/eu.txt locales 
+tools/camomilelocaledef.opt --file locales/it_IT_PREEURO.txt locales 
+tools/camomilelocaledef.opt --file locales/el_GR.txt locales 
+tools/camomilelocaledef.opt --file locales/kn.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/el.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/en_PH.txt locales 
+tools/camomilelocaledef.opt --file locales/nn_NO.txt locales 
+tools/camomilelocaledef.opt --file locales/it.txt locales 
+rm toolslib/colLexer.ml internal/uReStrLexer.ml toolslib/colParser.mli toolslib/colParser.ml
+files= &&\
+if [ -f camomileLibrary.cmx ]; then files=camomileLibrary.cmx; fi && \
+if [ -f camomileLibrary.cma ]; then files="camomileLibrary.cma $files"; fi && \
+if [ -f camomileLibrary.cmxa ]; then files="camomileLibrary.cmxa $files"; fi && \
+if [ -f camomileLibraryDefault.cmx ]; then files="camomileLibraryDefault.cmx $files"; fi && \
+if [ -f camomileLibraryDyn.cmx ]; then files="camomileLibraryDyn.cmx $files"; fi && \
+if [ -f camomile.cma ]; then files="camomile.cma $files"; fi&& \
+if [ -f camomile.cmxa ]; then files="camomile.cmxa $files"; fi&& \
+if [ -f camomile.cmxs ]; then files="camomile.cmxs $files"; fi&& \
+if [ -f camomile.a ]; then files="camomile.a $files"; fi && \
+ocamlfind install camomile $files META camomileLibrary.mli camomileLibraryDefault.mli camomileLibraryDyn.mli camomileLibrary.cmi camomileLibraryDefault.cmi camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDefault.cmi
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibrary.cmi
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDyn.mli
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDefault.mli
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibrary.mli
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibrary.cmx
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibrary.cma
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibrary.cmxa
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDefault.cmx
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomileLibraryDyn.cmx
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomile.cma
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomile.cmxa
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomile.cmxs
+Installed /home/opam/.opam/4.01.0/lib/camomile/camomile.a
+Installed /home/opam/.opam/4.01.0/lib/camomile/META
+mkdir -p '/home/opam/.opam/4.01.0/share'
+mkdir -p '/home/opam/.opam/4.01.0/share'/camomile
+mkdir -p '/home/opam/.opam/4.01.0/share'/camomile/database
+cp -f database/*.mar '/home/opam/.opam/4.01.0/share'/camomile/database || true
+mkdir -p '/home/opam/.opam/4.01.0/share'/camomile/charmaps
+cp -f charmaps/*.mar '/home/opam/.opam/4.01.0/share'/camomile/charmaps || true
+mkdir -p '/home/opam/.opam/4.01.0/share'/camomile/mappings
+cp -f mappings/*.mar '/home/opam/.opam/4.01.0/share'/camomile/mappings || true
+mkdir -p '/home/opam/.opam/4.01.0/share'/camomile/locales
+cp -f locales/*.mar '/home/opam/.opam/4.01.0/share'/camomile/locales || true
+Installing camomile.0.8.5.
+
+
+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Error report =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+These actions have been completed successfully
+ - install   camlimages.4.1.2
+ - install   camomile.0.8.5
+ - install   dypgen.20120619-1
+ - install   camlp4.4.01.0
+ - install   omake.0.9.8.6-0.rc1
+The following failed
+ - install   camlzip.1.05
+ - install   sqlite3-ocaml.2.0.6
+Due to the errors, the following have been cancelled
+ - install   patoline.0.1
+
+#==================== ERROR while installing camlzip.1.05 =====================#
+# opam-version         1.2.0~beta4
+# os                   linux
+# command              make all
+# path                 /home/opam/.opam/4.01.0/build/camlzip.1.05
+# compiler             4.01.0
+# exit-code            2
+# env-file             /home/opam/.opam/4.01.0/build/camlzip.1.05/camlzip-132-865888.env
+# stdout-file          /home/opam/.opam/4.01.0/build/camlzip.1.05/camlzip-132-865888.out
+# stderr-file          /home/opam/.opam/4.01.0/build/camlzip.1.05/camlzip-132-865888.err
+### stdout ###
+# ocamlc -g -c -ccopt -g -ccopt -I/usr/local/include zlibstubs.c
+### stderr ###
+# zlibstubs.c:18:18: fatal error: zlib.h: No such file or directory
+#  #include <zlib.h>
+#                   ^
+# compilation terminated.
+# make: *** [zlibstubs.o] Error 2
+
+
+#================= ERROR while installing sqlite3-ocaml.2.0.6 =================#
+# opam-version         1.2.0~beta4
+# os                   linux
+# command              ocaml setup.ml -build
+# path                 /home/opam/.opam/4.01.0/build/sqlite3-ocaml.2.0.6
+# compiler             4.01.0
+# exit-code            1
+# env-file             /home/opam/.opam/4.01.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-2933-6cc03f.env
+# stdout-file          /home/opam/.opam/4.01.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-2933-6cc03f.out
+# stderr-file          /home/opam/.opam/4.01.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-2933-6cc03f.err
+### stdout ###
+# ...[truncated]
+# Turn ocaml profile flag on: .......................... false
+# Compiler support generation of .cmxs.: ............... true
+# OCamlbuild additional flags: ......................... 
+# Strict compile-time checks: .......................... true
+# Create documentations: ............................... true
+# Compile tests executable and library and run them: ... false
+# ocamldoc: ............................................ /home/opam/.opam/4.01.0/bin/ocamldoc
+# 
+# /home/opam/.opam/4.01.0/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/4.01.0/lib/ocaml/ocamlbuild /home/opam/.opam/4.01.0/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/4.01.0/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
+# Failure: pkg-config failed for cflags.
+### stderr ###
+# Package sqlite3 was not found in the pkg-config search path.
+# Perhaps you should add the directory containing `sqlite3.pc'
+# to the PKG_CONFIG_PATH environment variable
+# No package 'sqlite3' found
+# E: Failure("Command ''/home/opam/.opam/4.01.0/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 2")
+
