20140812/roo/4.01.0: why

diff --git a/20140812/roo/4.01.0/raw/why b/20140812/roo/4.01.0/raw/why
--- a/20140812/roo/4.01.0/raw/why
+++ b/20140812/roo/4.01.0/raw/why
@@ -14920,3 +14920,223 @@ ocamlc.opt -w Z -dtypes -g -I src -I jc -I c -I java -I intf -I tools -I mix -I 
 ocamlopt.opt -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/opam/.opam/system/lib/lablgtk2 -I +threads -I /home/opam/.opam/system/lib/ocamlgraph -pack -o jc/jc.cmx src/ast.cmi src/lib.cmx src/rc.cmx src/loc.cmx src/ident.cmx src/print_real.cmx src/effect.cmx src/pp.cmx src/option_misc.cmx src/parser.cmx src/lexer.cmx src/report.cmx src/explain.cmx src/xml.cmx src/project.cmx src/why3_kw.cmx jc/output.cmx jc/jc_common_options.cmx jc/jc_stdlib.cmx jc/jc_envset.cmx jc/jc_region.cmx jc/jc_fenv.cmx jc/jc_constructors.cmx jc/jc_pervasives.cmx jc/jc_iterators.cmx jc/jc_type_var.cmx jc/jc_output_misc.cmx jc/jc_poutput.cmx jc/jc_output.cmx jc/jc_noutput.cmx
 ocamlopt.opt -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/opam/.opam/system/lib/lablgtk2 -I +threads -I /home/opam/.opam/system/lib/ocamlgraph -thread -o regtest.opt unix.cmxa str.cmxa threads.cmxa tools/regtest.ml
 make -C frama-c-plugin depend
+make[1]: Entering directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+Ocamldep     ./.depend
+make[1]: Leaving directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+make -C frama-c-plugin
+make[1]: Entering directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+Ocamlc       Jessie.cmi
+Ocamlc       jessie_config.cmo
+Ocamlc       jessie_options.cmi
+File "jessie_options.mli", line 32, characters 0-11:
+Warning 33: unused open Plugin.
+Ocamlc       jessie_options.cmo
+Ocamlc       jessie_integer.cmo
+Ocamlc       common.cmi
+File "common.mli", line 63, characters 0-72:
+Warning 32: unused value filter_alphanumeric.
+Ocamlc       common.cmo
+File "common.ml", line 333, characters 0-19:
+Warning 44: this open statement shadows the value identifier * (which is later used)
+File "common.ml", line 333, characters 0-19:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier && (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier = (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ^ (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier string_of_int (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ! (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ref (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier incr (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier >= (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier - (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ignore (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier || (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the type identifier ref (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier := (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier @ (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier invalid_arg (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier raise (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 45: this open statement shadows the constructor Exit (which is later used)
+Ocamlc       rewrite.cmo
+File "rewrite.ml", line 34, characters 0-14:
+Warning 45: this open statement shadows the label bstmts (which is later used)
+File "rewrite.ml", line 43, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+File "rewrite.ml", line 34, characters 0-14:
+Warning 45: this open statement shadows the constructor Tunion (which is later used)
+Ocamlc       norm.cmi
+Ocamlc       norm.cmo
+File "norm.ml", line 59, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+Ocamlc       retype.cmo
+Ocamlc       interp.cmi
+make[2]: Entering directory `/home/opam/.opam/system/build/why.2.33'
+make[2]: `jc/jc.cmo' is up to date.
+make[2]: Leaving directory `/home/opam/.opam/system/build/why.2.33'
+Ocamlc       interp.cmo
+File "interp.ml", line 190, characters 20-29:
+Warning 41: IMbounded belongs to several types: int_model Jc_env.int_model
+The first one was selected. Please disambiguate if this is wrong.
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier - (which is later used)
+File "interp.ml", line 46, characters 0-18:
+Warning 44: this open statement shadows the value identifier $ (which is later used)
+File "interp.ml", line 49, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier lsr (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier one (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier zero (which is later used)
+Ocamlc       register.cmo
+Packing      Jessie.cmo
+Packing      Jessie.cma
+Ocamlopt     jessie_config.cmx
+Ocamlopt     jessie_options.cmx
+Ocamlopt     jessie_integer.cmx
+Ocamlopt     common.cmx
+File "common.ml", line 333, characters 0-19:
+Warning 44: this open statement shadows the value identifier * (which is later used)
+File "common.ml", line 333, characters 0-19:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier && (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier = (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ^ (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier string_of_int (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ! (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ref (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier incr (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier >= (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier - (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier ignore (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier || (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the type identifier ref (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier := (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier @ (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier invalid_arg (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 44: this open statement shadows the value identifier raise (which is later used)
+File "common.ml", line 367, characters 0-15:
+Warning 45: this open statement shadows the constructor Exit (which is later used)
+Ocamlopt     rewrite.cmx
+File "rewrite.ml", line 34, characters 0-14:
+Warning 45: this open statement shadows the label bstmts (which is later used)
+File "rewrite.ml", line 43, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+File "rewrite.ml", line 34, characters 0-14:
+Warning 45: this open statement shadows the constructor Tunion (which is later used)
+Ocamlopt     norm.cmx
+File "norm.ml", line 59, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+Ocamlopt     retype.cmx
+Ocamlopt     interp.cmx
+File "interp.ml", line 190, characters 20-29:
+Warning 41: IMbounded belongs to several types: int_model Jc_env.int_model
+The first one was selected. Please disambiguate if this is wrong.
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier - (which is later used)
+File "interp.ml", line 46, characters 0-18:
+Warning 44: this open statement shadows the value identifier $ (which is later used)
+File "interp.ml", line 49, characters 0-11:
+Warning 44: this open statement shadows the value identifier constant_expr (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier lsr (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier + (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier one (which is later used)
+File "interp.ml", line 50, characters 0-19:
+Warning 44: this open statement shadows the value identifier zero (which is later used)
+Ocamlopt     register.cmx
+Packing      Jessie.cmx
+Packing      Jessie.cmxs
+make[1]: Leaving directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+mkdir -p /home/opam/.opam/system/bin
+cp -f bin/why.opt /home/opam/.opam/system/bin/why
+cp -f bin/why-config.opt /home/opam/.opam/system/bin/why-config
+cp -f bin/jessie.opt /home/opam/.opam/system/bin/jessie
+cp -f bin/krakatoa.opt /home/opam/.opam/system/bin/krakatoa
+cp -f bin/gwhy.sh /home/opam/.opam/system/bin/gwhy
+cp -f bin/why2html.opt /home/opam/.opam/system/bin/why2html
+cp -f bin/why-dp.opt /home/opam/.opam/system/bin/why-dp
+cp -f bin/why-cpulimit /home/opam/.opam/system/bin/why-cpulimit
+cp -f bin/rv_merge.opt /home/opam/.opam/system/bin/rv_merge
+cp -f bin/why-obfuscator.opt /home/opam/.opam/system/bin/why-obfuscator
+cp -f bin/why-stat.opt /home/opam/.opam/system/bin/why-stat
+cp -f bin/tool-stat.opt /home/opam/.opam/system/bin/tool-stat
+cp -f bin/simplify2why.opt /home/opam/.opam/system/bin/simplify2why
+if test -f bin/gwhy.opt; then \
+		cp -f bin/gwhy.opt /home/opam/.opam/system/bin/gwhy-bin; \
+	fi
+mkdir -p /home/opam/.opam/system/lib/why/lib/why/why
+cp -f lib/why/prelude.why lib/why/bool.why lib/why/integer.why lib/why/divisions.why lib/why/real.why lib/why/arrays.why lib/why/jessie.why lib/why/jessie_bitvectors.why lib/why/mybag.why lib/why/mix.why lib/why/floats_common.why lib/why/floats_strict.why lib/why/floats_full.why lib/why/floats_multi_rounding.why  /home/opam/.opam/system/lib/why/lib/why/why
+rm -rf /home/opam/.opam/system/lib/why/lib/why/why3
+mkdir -p /home/opam/.opam/system/lib/why/lib/why/why3
+cp -f lib/why3/why3.conf lib/why3/coq.drv lib/why3/jessie3theories.why lib/why3/jessie3.mlw lib/why3/jessie3_integer.why /home/opam/.opam/system/lib/why/lib/why/why3
+mkdir -p /home/opam/.opam/system/lib/why/lib/jessie
+cp -f jc/jc.cmo jc/jc.cmx jc/jc.o jc/jc_ast.cmi jc/jc_env.cmi jc/jc.cmi src/lib.cmi src/rc.cmi src/loc.cmi src/ident.cmi src/print_real.cmi src/effect.cmi src/pp.cmi src/option_misc.cmi src/parser.cmi src/lexer.cmi src/report.cmi src/explain.cmi src/xml.cmi src/project.cmi src/why3_kw.cmi jc/output.cmi jc/jc_common_options.cmi jc/jc_stdlib.cmi jc/jc_envset.cmi jc/jc_region.cmi jc/jc_fenv.cmi jc/jc_constructors.cmi jc/jc_pervasives.cmi jc/jc_iterators.cmi jc/jc_type_var.cmi jc/jc_output_misc.cmi jc/jc_poutput.cmi jc/jc_output.cmi jc/jc_noutput.cmi /home/opam/.opam/system/lib/why/lib/jessie
+cd lib; cp -rf java_api /home/opam/.opam/system/lib/why/lib/why
+cd lib; cp -rf javacard_api /home/opam/.opam/system/lib/why/lib/why
+mkdir -p /home/opam/.opam/system/lib/why/lib/why/images
+cp -f lib/images/*.png /home/opam/.opam/system/lib/why/lib/why/images
+mkdir -p /home/opam/.opam/system/lib/why/lib/why/emacs
+cp -f lib/emacs/why.el /home/opam/.opam/system/lib/why/lib/why/emacs
+find /home/opam/.opam/system/lib/why/lib -name CVS | xargs rm -f -r
+mkdir -p /home/opam/.opam/system/lib/why/share/man/man1
+cp -f doc/*.1 /home/opam/.opam/system/lib/why/share/man/man1
+if test -w "/home/opam/.opam/system/lib/coq" ; then \
+	  rm -f "/home/opam/.opam/system/lib/coq"/user-contrib/Why*.v* ; \
+	  rm -f "/home/opam/.opam/system/lib/coq"/user-contrib/caduceus*.v* "/home/opam/.opam/system/lib/coq"/user-contrib/Caduceus*.v* ; \
+	  rm -f "/home/opam/.opam/system/lib/coq"/user-contrib/jessie*.v* "/home/opam/.opam/system/lib/coq"/user-contrib/Jessie*.v* ; \
+	  mkdir -p "/home/opam/.opam/system/lib/coq"/user-contrib/Why ; \
+	  cp -f lib/coq/WhyInt.vo lib/coq/WhyArrays.vo  lib/coq/WhyBool.vo lib/coq/WhyTuples.vo  lib/coq/WhyPermut.vo lib/coq/WhyCoqCompat.vo lib/coq/WhySorted.vo lib/coq/WhyExn.vo lib/coq/WhyLemmas.vo  lib/coq/WhyTactics.vo lib/coq/WhyPrelude.vo lib/coq/WhyCM.vo lib/coq/Why.vo lib/coq/WhyReal.vo lib/coq/Jessie_memory_model.vo lib/coq/jessie_why.vo  "/home/opam/.opam/system/lib/coq"/user-contrib/Why ; \
+	else \
+	  echo "Cannot copy to Coq standard library. Add \"-R /home/opam/.opam/system/lib/why/lib/why/coq Why\" to Coq options." ;\
+	fi
+mkdir -p /home/opam/.opam/system/lib/why/lib/why/coq
+cp -f lib/coq/WhyInt.vo lib/coq/WhyArrays.vo  lib/coq/WhyBool.vo lib/coq/WhyTuples.vo  lib/coq/WhyPermut.vo lib/coq/WhyCoqCompat.vo lib/coq/WhySorted.vo lib/coq/WhyExn.vo lib/coq/WhyLemmas.vo  lib/coq/WhyTactics.vo lib/coq/WhyPrelude.vo lib/coq/WhyCM.vo lib/coq/Why.vo lib/coq/WhyReal.vo lib/coq/Jessie_memory_model.vo lib/coq/jessie_why.vo  /home/opam/.opam/system/lib/why/lib/why/coq
+make -C frama-c-plugin install
+make[1]: Entering directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+Copying to   /home/opam/.opam/system/lib/frama-c/lib/frama-c/plugins
+Copying to   /home/opam/.opam/system/bin
+make[1]: Leaving directory `/home/opam/.opam/system/build/why.2.33/frama-c-plugin'
+Installing why.2.33.
