centos-7/4.02.0/20141002: qocamlbrowser

diff --git a/centos-7/4.02.0/20141002/raw/patoline b/centos-7/4.02.0/20141002/raw/patoline
--- a/centos-7/4.02.0/20141002/raw/patoline
+++ b/centos-7/4.02.0/20141002/raw/patoline
@@ -2889,3 +2889,143 @@ tools/camomilelocaledef.opt --file locales/ca.txt locales
 tools/camomilelocaledef.opt --file locales/en_ZW.txt locales 
 tools/camomilelocaledef.opt --file locales/ar_DZ.txt locales 
 tools/camomilelocaledef.opt --file locales/lt.txt locales 
+tools/camomilelocaledef.opt --file locales/hy_AM.txt locales 
+tools/camomilelocaledef.opt --file locales/sh.txt locales 
+tools/camomilelocaledef.opt --file locales/es_DO.txt locales 
+tools/camomilelocaledef.opt --file locales/da_DK.txt locales 
+tools/camomilelocaledef.opt --file locales/es_PY.txt locales 
+tools/camomilelocaledef.opt --file locales/en_MH.txt locales 
+tools/camomilelocaledef.opt --file locales/en_ZA.txt locales 
+tools/camomilelocaledef.opt --file locales/hy_AM_REVISED.txt locales 
+tools/camomilelocaledef.opt --file locales/he.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/fr_CH.txt locales 
+tools/camomilelocaledef.opt --file locales/mr_IN.txt locales 
+tools/camomilelocaledef.opt --file locales/root.txt locales 
+tools/camomilelocaledef.opt --file locales/eu_ES.txt locales 
+tools/camomilelocaledef.opt --file locales/no_NO_NY.txt locales 
+tools/camomilelocaledef.opt --file locales/es_BO.txt locales 
+tools/camomilelocaledef.opt --file locales/es_EC.txt locales 
+tools/camomilelocaledef.opt --file locales/om_KE.txt locales 
+tools/camomilelocaledef.opt --file locales/eu.txt locales 
+tools/camomilelocaledef.opt --file locales/it_IT_PREEURO.txt locales 
+tools/camomilelocaledef.opt --file locales/el_GR.txt locales 
+tools/camomilelocaledef.opt --file locales/kn.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/el.txt locales 
+Warning : normalization option is not supported
+tools/camomilelocaledef.opt --file locales/en_PH.txt locales 
+tools/camomilelocaledef.opt --file locales/nn_NO.txt locales 
+tools/camomilelocaledef.opt --file locales/it.txt locales 
+rm toolslib/colLexer.ml internal/uReStrLexer.ml toolslib/colParser.mli toolslib/colParser.ml
+files= &&\
+if [ -f camomileLibrary.cmx ]; then files=camomileLibrary.cmx; fi && \
+if [ -f camomileLibrary.cma ]; then files="camomileLibrary.cma $files"; fi && \
+if [ -f camomileLibrary.cmxa ]; then files="camomileLibrary.cmxa $files"; fi && \
+if [ -f camomileLibraryDefault.cmx ]; then files="camomileLibraryDefault.cmx $files"; fi && \
+if [ -f camomileLibraryDyn.cmx ]; then files="camomileLibraryDyn.cmx $files"; fi && \
+if [ -f camomile.cma ]; then files="camomile.cma $files"; fi&& \
+if [ -f camomile.cmxa ]; then files="camomile.cmxa $files"; fi&& \
+if [ -f camomile.cmxs ]; then files="camomile.cmxs $files"; fi&& \
+if [ -f camomile.a ]; then files="camomile.a $files"; fi && \
+ocamlfind install camomile $files META camomileLibrary.mli camomileLibraryDefault.mli camomileLibraryDyn.mli camomileLibrary.cmi camomileLibraryDefault.cmi camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDyn.cmi
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDefault.cmi
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibrary.cmi
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDyn.mli
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDefault.mli
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibrary.mli
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibrary.cmx
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibrary.cma
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibrary.cmxa
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDefault.cmx
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomileLibraryDyn.cmx
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomile.cma
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomile.cmxa
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomile.cmxs
+Installed /home/opam/.opam/4.02.0/lib/camomile/camomile.a
+Installed /home/opam/.opam/4.02.0/lib/camomile/META
+mkdir -p '/home/opam/.opam/4.02.0/share'
+mkdir -p '/home/opam/.opam/4.02.0/share'/camomile
+mkdir -p '/home/opam/.opam/4.02.0/share'/camomile/database
+cp -f database/*.mar '/home/opam/.opam/4.02.0/share'/camomile/database || true
+mkdir -p '/home/opam/.opam/4.02.0/share'/camomile/charmaps
+cp -f charmaps/*.mar '/home/opam/.opam/4.02.0/share'/camomile/charmaps || true
+mkdir -p '/home/opam/.opam/4.02.0/share'/camomile/mappings
+cp -f mappings/*.mar '/home/opam/.opam/4.02.0/share'/camomile/mappings || true
+mkdir -p '/home/opam/.opam/4.02.0/share'/camomile/locales
+cp -f locales/*.mar '/home/opam/.opam/4.02.0/share'/camomile/locales || true
+Installing camomile.0.8.5.
+
+#==================== ERROR while installing camlzip.1.05 =====================#
+# opam-version         1.2.0~beta4
+# os                   linux
+# command              make all
+# path                 /home/opam/.opam/4.02.0/build/camlzip.1.05
+# compiler             4.02.0
+# exit-code            2
+# env-file             /home/opam/.opam/4.02.0/build/camlzip.1.05/camlzip-1753-865888.env
+# stdout-file          /home/opam/.opam/4.02.0/build/camlzip.1.05/camlzip-1753-865888.out
+# stderr-file          /home/opam/.opam/4.02.0/build/camlzip.1.05/camlzip-1753-865888.err
+### stdout ###
+# ocamlc -g -c -ccopt -g -ccopt -I/usr/local/include zlibstubs.c
+### stderr ###
+# zlibstubs.c:18:18: fatal error: zlib.h: No such file or directory
+#  #include <zlib.h>
+#                   ^
+# compilation terminated.
+# make: *** [zlibstubs.o] Error 2
+
+
+
+#================= ERROR while installing sqlite3-ocaml.2.0.6 =================#
+# opam-version         1.2.0~beta4
+# os                   linux
+# command              ocaml setup.ml -build
+# path                 /home/opam/.opam/4.02.0/build/sqlite3-ocaml.2.0.6
+# compiler             4.02.0
+# exit-code            1
+# env-file             /home/opam/.opam/4.02.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-4554-6cc03f.env
+# stdout-file          /home/opam/.opam/4.02.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-4554-6cc03f.out
+# stderr-file          /home/opam/.opam/4.02.0/build/sqlite3-ocaml.2.0.6/sqlite3-ocaml-4554-6cc03f.err
+### stdout ###
+# ...[truncated]
+# Turn ocaml profile flag on: .......................... false
+# Compiler support generation of .cmxs.: ............... true
+# OCamlbuild additional flags: ......................... 
+# Strict compile-time checks: .......................... true
+# Create documentations: ............................... true
+# Compile tests executable and library and run them: ... false
+# ocamldoc: ............................................ /home/opam/.opam/4.02.0/bin/ocamldoc
+# 
+# /home/opam/.opam/4.02.0/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/4.02.0/lib/ocaml/ocamlbuild /home/opam/.opam/4.02.0/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/4.02.0/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
+# Failure: pkg-config failed for cflags.
+### stderr ###
+# ...[truncated]
+# Warning 3: deprecated: Lazy.lazy_from_fun
+# File "setup.ml", line 247, characters 8-26:
+# Warning 3: deprecated: String.set
+# File "setup.ml", line 2502, characters 6-24:
+# Warning 3: deprecated: Lazy.lazy_from_fun
+# Package sqlite3 was not found in the pkg-config search path.
+# Perhaps you should add the directory containing `sqlite3.pc'
+# to the PKG_CONFIG_PATH environment variable
+# No package 'sqlite3' found
+# E: Failure("Command ''/home/opam/.opam/4.02.0/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 2")
+
+
+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Error report =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+These actions have been completed successfully
+ - install   camomile.0.8.5
+ - install   dypgen.20120619-1
+ - install   camlimages.4.2.0
+ - install   camlp4.4.02.0+1
+ - install   omake.0.9.8.6-0.rc1
+The following failed
+ - install   camlzip.1.05
+ - install   sqlite3-ocaml.2.0.6
+Due to the errors, the following have been cancelled
+ - install   patoline.0.1
+
+The former state can be restored with opam switch import "/home/opam/.opam/4.02.0/backup/state-20140902084846.export"
+'opam install patoline' failed.
